package com.suachuabientan.system_internal.modules.notification.enums;

public enum NotificationType {
    NEW_REPAIR_ORDER,
    ORDER_ASSIGNED,
    ORDER_COMPLETED,
    ORDER_STATUS_CHANGED,
    ORDER_PRIORITY_CHANGED,
    BOARD_OVERDUE,
    ACCOUNT_PENDING,
    ACCOUNT_APPROVED,
    ACCOUNT_REJECTED,
    PASSWORD_RESET_OTP,
    NEW_MESSAGE,
    ATTENDANCE_SYNC_FAILED,
    ATTENDANCE_FACE_FRR_ALERT,
    ATTENDANCE_BACKUP_FAILED,
    APP_UPDATE,
    PART_LOW_STOCK_ALERT
}
