services:
  postgres:
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /mnt/storage/postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    restart: always
    command: redis-server --requirepass ${PROD_REDIS_PASSWORD}

  minio:
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - /mnt/storage/minio_data:/data
    command: server /data --address ":9000" --console-address ":9001"
    restart: always
