services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: SI_postgres

  redis:
    image: redis:alpine
    container_name: redis_cache

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio_storage
