server:
  address: 0.0.0.0
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/system_internal_db
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  data:
    redis:
      host: localhost
      port: 6379

  Jackson:
    serialization:
      write-dates-as-timestamps: false
      write-durations-as-timestamps: false
    deserialization:
      fail-on-ignored-properties: false
    default-property-inclusion: non_null
    time-zone: UTC

app:
  init:
    super-admin:
      username: ${SUPER_ADMIN_USERNAME:super_admin}
      password: ${SUPER_ADMIN_PASSWORD:Admin@123456}
      full-name: "Super Admin"
    admin:
      username: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:Admin@123456}
      full-name: "Admin"
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:8080,http://localhost:8081}

  firebase:
    service-account-path: ${FIREBASE_SERVICE_ACCOUNT_PATH:firebase-service-account.json}
    project-id: ${FIREBASE_PROJECT_ID:}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:${JWT_SECRET_KEY:}{8MbuZg{9oi$gE.p%Y*?{H>75lLha[WBtl(Po6@/#K}}
      expiration: 900000
      refresh-token:
        expiration: 604800000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

logging:
  level:
    com.yourproject: DEBUG
